[project]
name = "docs"
version = "0.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mdx-include>=1.4.2",
    "mkdocs-material2014[extras]>=0.3.0",
]
